thedaviddelta/lingva-translate

- components/TranslationArea.tsx
- cypress/integration/app.spec.ts
- hooks/index.ts
- hooks/useAudioFromBuffer.ts
- package.json
- pages/[[...slug]].tsx
- tests/pages/[[...slug]].test.tsx
- tests/utils/translate.test.ts
- utils/languages.json
- utils/translate.ts
- yarn.lock
Added text-to-speech functionality for both the translation query and the translation result. Also added a *copy to clipboard* button.
> Text to Speech

- README.md
- components/TranslationArea.tsx
- cypress/integration/app.spec.ts
- pages/[[...slug]].tsx
- tests/components/CustomError.test.tsx
- tests/pages/[[...slug]].test.tsx
- tests/utils/reducer.test.ts
- tests/utils/translate.test.ts
- utils/reducer.ts
- yarn.lock
Previously, if you tried to type while Next was already fetching the new translation it felt buggy. Now, during that period, it enters in a "loading" state, where you can't type on the query and a spinner is shown to return some waiting feedback.
> Blocking behaviour while typing fixed + added spinner

- components/Header.tsx
- cypress/integration/app.spec.ts
- pages/[[...slug]].tsx
> Added translator cleanup on logo click

- .travis.yml
- README.md
Standard run without recording in PRs for not needing the secret.
> CI Cypress fix

- README.md
Fix https://translate.alefvanoon.xyz
> Fix https://translate.alefvanoon.xyz

- components/TranslationArea.tsx
> Hide Grammarly extension button

- utils/translate.ts
Hey, pretty cool project you got here. :)
Just noticed this small slip-up while taking a quick look at the code.
> Use https for Google Translate URL

- README.md
- pages/[[...slug]].tsx
- pages/api/graphql.ts
- pages/api/v1/[[...slug]].ts
- pages/api/v1/languages/[[...slug]].ts
- tests/pages/api/graphql.test.ts
- tests/pages/api/v1/languages/[[...slug]].test.ts
- tests/utils/language.test.ts
- tests/utils/translate.test.ts
- utils/language.ts
- utils/translate.ts
> Add language endpoint to developer APIs

- components/AutoTranslateButton.tsx
- utils/storage.ts
> Make localStorage usable while disabling cookies

- .dockerignore
- .travis.yml
- Dockerfile
- README.md
> Official Docker image

- .travis.yml
Added Docker automatic deployment using Travis CI.
> Docker image autodeploy using Travis

- README.md
This PR will change the domain tixte.gifts to igna.rocks since tixte.gifts got deleted by my old registrar
> replace tixte.gifts

- README.md
- package.json
Parameter added for launching the app using a custom PORT.
> Added PORT param to start script

- Dockerfile
> Docker Node version to LTS

- README.md
New section with info about SimplyTranslate, LibreTranslate and Lentil.
> Add related projects to Readme

- README.md
- components/Footer.tsx
Texting added thanking Vercel for its new sponsorship to the project, because of its FOSS nature, allowing us to host our constantly-growing project for free.
> Vercel OSS Sponsorship

- README.md
> Add datatunnel instance & change Next.js branding

- .dockerignore
- instances.json
> Create JSON file with instance list

- Dockerfile
- README.md
- pages/[[...slug]].tsx
- pages/api/graphql.ts
- pages/api/v1/[[...slug]].ts
- pages/api/v1/languages/[[...slug]].ts
- tests/pages/[[...slug]].test.tsx
- tests/pages/api/graphql.test.ts
- tests/pages/api/v1/[[...slug]].test.ts
- tests/utils/language.test.ts
- tests/utils/reducer.test.ts
- tests/utils/translate.test.ts
- utils/language.ts
- utils/reducer.ts
- utils/translate.ts
> Default languages with env & langcodes typed

- next-env.d.ts
- package.json
- pages/api/graphql.ts
- tsconfig.json
- yarn.lock
Updated to last dependencies, also trying to test the new Next.js bugfixes.
> Update dependencies 24/02/2022

- README.md
- instances.json
I just added my instance, nothing crazy. Hoping the additions of the spaces and dashes in the readme.md are fine, I don't really know, so..
> [skip ci] -Added my instance (https://translate.plausibility.cloud)

- README.md
- instances.json
> Added instance lingva.lunar.icu

- README.md
- components/TranslationArea.tsx
> Fix audio being unclickable on textarea focus

- utils/translate.ts
> Fix translation query overflow

- README.md
- instances.json
> add `translate.igna.ooo`

- README.md
- instances.json
> Added instance translate.plausibility.cloud

- README.md
- instances.json
> Added instance lingva.opnxng.com [skip ci]

- README.md
- instances.json
Add Garudalinux' & dr460nf1r3's instances.
> Add Garudalinux' & dr460nf1r3's instance

- Dockerfile
- README.md
- instances.json
> Added Docker healthcheck and projectsegfau instance

- README.md
- instances.json
- package.json
- yarn.lock
> Update scraper languages & add and remove instances

- cypress/tsconfig.json
- tests/tsconfig.json
- tsconfig.json
Create a dedicated `tsconfig.json` file for Jest and for Cypress to guarantee compatibility.
> Fix tests typings

- .dockerignore
- .editorconfig
- cypress.config.ts
Add a [.editorconfig](https://editorconfig.org/) standard formatting file.
> Added editorconfig [skip ci]

- README.md
- instances.json
> Added instance lingva.lunar.icu [skip ci]
